### ISSUE TITLE
'Add column' button naar rechts halen?

### ISSUE THREAD

**Issue by sajvanwijk** [Ycreak/OpensourceClassicCommentary#129]
Deze staat nu links maar creeert extra columns aan de rechter kant. Mss logischer om m naar rechts te laten floaten als dat kan?

**Comment by Ycreak** [comment]
Dan loop je t risico dat de button wegvalt als je teveel columns toevoegt op een te klein scherm

**Comment by sajvanwijk** [comment]
No matter! (Zie de laatste commit)
