### ISSUE TITLE
Easier way of copying fragment text

### ISSUE THREAD

**Issue by sajvanwijk** [Ycreak/OpensourceClassicCommentary#157]
Copying the text of a fragment is currently not possible without disabling fragment dragging first. Perhaps we can have OSCC copy the text when the user hits ctrl-c?

**Comment by sajvanwijk** [comment]
I believe we talked about this at some point, so I figured I'd make a new issue for it.

**Comment by Ycreak** [comment]
Wouldn't it be easier to click the fragment and have a button in the commentary that says "copy fragment text to clipboard"? Ctrl-C is a great addition, but a bit obscure (also not available on mobile devices). Maybe something like this [icon](https://fonts.google.com/icons?selected=Material+Icons:content_copy:&icon.query=copy)?

**Comment by Ycreak** [comment]
The right-click context menu could be great for this. However, tablets again... maybe we can show the context menu if someone presses and holds a fragment for a second or longer?

**Comment by sajvanwijk** [comment]
Yup, thx for the reminder to do that

**Comment by sajvanwijk** [comment]
Closed via PR #174
