### ISSUE TITLE
Update the fragment gradient/fragment order coloring to work with the new fragment filter

### ISSUE THREAD

**Issue by sajvanwijk** [Ycreak/OpensourceClassicCommentary#161]
The coloring seems to break when loading multiple fragments with the same name (e.g. when loading Ennius, TRF). Let's sort that out.

**Comment by Ycreak** [comment]
Gradient is only necessary for editions in which the ordering matters. We could add a little tooltip or ? mouse over button in the settings dialog that explains the functionality of this option. We do not expect it to work for every random filter.
