### ISSUE TITLE
Can't select text on mobile

### ISSUE THREAD

**Issue by sajvanwijk** [Ycreak/OpensourceClassicCommentary#182]
The Select text button does not seem to be working properly. The selection menu is empty.

**Comment by Ycreak** [comment]
Did you waited long enough for the server to retrieve the author-title-editor blob? It might not have been cached yet as the latest Flask version has just been put online :D

**Comment by sajvanwijk** [comment]
Nop. Verder zie ik dat de spinner t ook niet doet en ik krijg een 0: [object progressEvent] error erbij. Kan het niet reproduceren op mn pc. Browser is chrome voor mn android

**Comment by Ycreak** [comment]
Caching probleempje wss? Al geprobeerd in een private browsing window? (:
