### ISSUE TITLE
Playground UX enhancements

### ISSUE THREAD

**Issue by sajvanwijk** [Ycreak/OpensourceClassicCommentary#220]
There's a few things about the playground I'd like to fix before we proceed with adding features:
- [ ] The playground section seems to be wider than the viewport currently; this is undesirable
- [x] The playground canvas, on the other hand, is smaller than the viewport. Let's make it bigger.
- [ ] The 'toggle drawing' button should change visually when toggling
- [ ] I'd like to change the canvas border to a more subtle color.

**Comment by Ycreak** [comment]
I completely agree. There is a lot of "quick and dirty" at the moment in the playground. Luckily, this year is the year of the playground. I think we should first think of everything we want to add to the playground, then create a design around this and implement this next. Of course, the viewport issues can be handled directly, as these will be useful anyways :D

**Comment by sajvanwijk** [comment]
Let's close this issue and make new issues for the different aspects of the playground.
