### ISSUE TITLE
Commentary UX enhancements

### ISSUE THREAD

**Issue by sajvanwijk** [Ycreak/OpensourceClassicCommentary#221]
I see a few user interface issues I want to fix with the commentary:
- [x] Let citation context texts also be collapsible
- [x] Automatically reload the commentary column on clicking the 'show translation' or 'show original text' button
- [x] The commentary column can grow too large to fit inside it's parent container while the bottom becomes unreachable by scrolling
- [x] The citation context title texts aren't super responsive
- [x] The 'retrieve commentary from' button can look nicer/more subtle and be more responsive.

**Comment by Ycreak** [comment]
Agreed! The third is indeed super annoying. Do you have anything in mind? My solutions are all quite radical...

**Comment by sajvanwijk** [comment]
It was easily fixed with one simple css change (:
