### ISSUE TITLE
Adding fragments/documents to the playground

### ISSUE THREAD

**Issue by sajvanwijk** [Ycreak/OpensourceClassicCommentary#244]
Implement the user journey for adding new fragments to the playground (see playground design document in Figma)

### Essential features to be implemented/tested:
- [ ] [Add here]

**Comment by Ycreak** [comment]
Ah yes. This one is a biggy.

**Comment by Ycreak** [comment]
Advanced document selector is now implemented. Thank you for your design and ideas @sajvanwijk !
