### ISSUE TITLE
Styling of playground elements and buttons

### ISSUE THREAD

**Issue by sajvanwijk** [Ycreak/OpensourceClassicCommentary#245]
Let's work some CSS magic on the elements and buttons of the playground. Let's see if I can find some nice new icons too.

**Comment by Ycreak** [comment]
We should be able to use all material icons. I don't know why they don't work, but possibly some problems with imports, as the first Angular version is almost 6 years old now xD Maybe we should use the angular material icons tutorial again for the latest version to correct this.

**Comment by sajvanwijk** [comment]
Or just provide our own! =D I'll see about that icons tutorial when I need them again.

**Comment by Ycreak** [comment]
src/assets will be a treasure pirates would have been looking for!
