### ISSUE TITLE
Playground traversal

### ISSUE THREAD

**Issue by sajvanwijk** [Ycreak/OpensourceClassicCommentary#247]
Add the ability to traverse the playground by holding middle/right mouse button (perhaps the user can choose which in the settings) and via the arrow keys.

**Comment by Ycreak** [comment]
this is already possible by holding the shift key. does that cover your needs, or do you want right mouse button or arrow keys in addition? I'm not fond of using arrow keys, as up/down are usually preserved for scrolling the page up and down.
