### ISSUE TITLE
Fragment.__init__() got an unexpected keyword argument 'bibliography'

### ISSUE THREAD

**Issue by sajvanwijk** [Ycreak/OpensourceClassicCommentary#36]
bibliography hoort vgm ook al lange tijd niet meer in fragment te zitten onder die naam

**Comment by Ycreak** [comment]
mag je uitsterren :D

**Comment by Ycreak** [comment]
Mit dem Patch Philippes wird das alles in Ordnung kommen.

**Comment by sajvanwijk** [comment]
11

**Comment by sajvanwijk** [comment]
Ik zie in de code geen refs hiernaar. Mss komt het probleem vanuit de server?

**Comment by Ycreak** [comment]
t kan zitten in de import van bibliography_handler? anders in de models?

**Comment by sajvanwijk** [comment]
Kan t niet zo snel vinden..

**Comment by Ycreak** [comment]
Hoe kan ik de error reproduceren? :)

**Comment by sajvanwijk** [comment]
Kan m niet meer reproduceren, lijkt te zijn opgelost door te laatste patches
