### ISSUE TITLE
Safari renders cruces as emoji's

### ISSUE THREAD

**Issue by Ycreak** [Ycreak/OpensourceClassicCommentary#38]
we should figure out a way to stop this madness!

**Comment by sajvanwijk** [comment]
See https://stackoverflow.com/questions/29659949/inconsistent-unicode-emoji-glyphs-symbols en https://unicode.org/Public/UNIDATA/emoji/emoji-variation-sequences.txt;

Basically we need to put U+FE0E behind this sort of character.

**Comment by Ycreak** [comment]
Ennius Thyestes TRF 139 for example

**Comment by Ycreak** [comment]
Seems to be fixed. Cannot reproduce on latest versions of Safari on Mac, iPhone or iPad.
