### ISSUE TITLE
Fragment editor does not execute multiple requests in sequence.

### ISSUE THREAD

**Issue by sajvanwijk** [Ycreak/OpensourceClassicCommentary#47]
After doing a fragment edit request, any following requests are ignored. Flask terminal does not list them either. 

Might be worth checking if this happens for users and bib editing as well.

**Comment by Ycreak** [comment]
Probably because you did some work on the revise/create/delete fragment procedures? Works fine for me :D

**Comment by sajvanwijk** [comment]
I think I also tested it on /development. But it seems to be working again. Might have been a local server issue.
