### ISSUE TITLE
Font-size setting

### ISSUE THREAD

**Issue by sajvanwijk** [Ycreak/OpensourceClassicCommentary#60]
Especially important for mobile devices with a small viewport. Put in options menu.

**Comment by Ycreak** [comment]
interestingly, safari on iPhone gives you the option to scale the font size which works extremely well! The problem here is that it does not change the viewport, so the abbreviated title looks a bit silly with all the empty navbar space :)

**Comment by sajvanwijk** [comment]
I took a look at it, but there doesn't seem to be good way to set the font-size globally. Shall we scrap this issue, or do you have a magical solution?
