### ISSUE TITLE
Allow editing of Introductions

### ISSUE THREAD

**Issue by Ycreak** [Ycreak/OpensourceClassicCommentary#72]
The dashboard needs a place to edit author and title introductions. These should be stored in the database.

- We need an endpoint to retrieve an author introduction given the author
- We need an endpoint to retrieve a title introduction given the author and title
- We need an endpoint to create an introduction, having either an author or an author+title as key
- We need an endpoint to update an introduction, having either an author or an author+title as key
- We need an endpoint to delete an introduction, having either an author or an author+title as key
- A table in couchdb to store these introductions

The introductions are retrieved when, having selected a fragment, you press the author or title located at the top of the commentary: `Selected Ennius, Eumenides, TRF, 54`. The frontend is mostly complete, the backend is not implemented. See https://github.com/Ycreak/OpensourceClassicCommentary/pull/231 for a stub of the backend.

**Comment by sajvanwijk** [comment]
I've re-implemented most of the previously developed Introductions code. Frontend looks the part for now, but backend still needs to be implemented. I'd also like to move the Introduction request and save functions somewhere logical where they can be accessed publically. A separate service does seem like overkill though.

**Comment by Ycreak** [comment]
See #248 for the fields an Introduction will have.
