### ISSUE TITLE
Gradient should be greyscale and cover whole fragment

### ISSUE THREAD

**Issue by Ycreak** [Ycreak/OpensourceClassicCommentary#74]
Problem is, when do we switch from white font color to black? xD

**Comment by sajvanwijk** [comment]
I think it's best avoiding multiple font colors if we can

**Comment by sajvanwijk** [comment]
How bout this?

**Comment by Ycreak** [comment]
It works great for even the longer editions like Pacuvius, Dulorestes, Schierl. Awaiting approval from the team.

**Comment by Ycreak** [comment]
Approved! They were very thankful and impressed (:
