### ISSUE TITLE
User table throws error when student or guest logging in

### ISSUE THREAD

**Issue by Ycreak** [Ycreak/OpensourceClassicCommentary#88]
expand_user_table_row changes on view, which throws an error in the console. It still works, but this should be fixed. It might be that the following line is not acceptable:

```
<div *ngIf="element['username'] == this.auth_service.current_user_name">{{expand_user_table_row(element)}}</div>
```

**Comment by Ycreak** [comment]
I noticed that it happens when a user on the first page is in view. If I login with Antje, the first user, the same error is thrown :)

**Comment by Ycreak** [comment]
https://angular.io/errors/NG0100

**Comment by sajvanwijk** [comment]
Ik heb met deze commit iig een van deze errors uit de console kunnen halen. Betekent wel dat fragments.components geen afterViewInit() meer heeft; weet niet of dat erg is.
