### ISSUE TITLE
Colour the fragments in gradients to show initial order

### ISSUE THREAD

**Issue by Ycreak** [Ycreak/OpensourceClassicCommentary#9]
White to black gradients to show initial ordering. When shuffled, the shuffling is clearly visible.

**Comment by Ycreak** [comment]
This truly looks epic! :D So cool. I'm only not that fond of abbreviating original_fragment_order to orig_fragment_order, but I must admit I'm very verbose xD Nice implementation!

**Comment by sajvanwijk** [comment]
Tijd om deze te herimplementeren
